### ISSUE TITLE
How to get Blendshape value in Quest Pro Movement SDK (OpenXR)?

### ISSUE THREAD

**Issue by SlimeVRX** [JsMarq96/Understanding-Tiled-Volume-Rendering#1]
Hello @JsMarq96

I need you help me get Blendshape value in Quest Pro Movement SDK (OpenXR)

![image](https://user-images.githubusercontent.com/99313947/200458486-d98df8c2-9077-4846-9e9e-18ec3e2d7c8b.png)

Source: https://twitter.com/SadlyItsBradley/status/1585648999918354437

There is a sample in your code: https://github.com/JsMarq96/Understanding-Tiled-Volume-Rendering/blob/ee294f2407da501274c6abd301fbfd8eec5575fc/OpenXR/Include/openxr/fb_face_tracking.h#L63

How to do this? Please help me! Thank you very much!

**Comment by JsMarq96** [comment]
Hi!
Sorry, just read the issue.. I need to fix my github notifications ASAP!

I am not using any of the Quest Pro functionality, the code that you are referencing is about the Meta's OpenXR SDK; that I am using for a custom engine; but I am focusing on the Quest 2.

Idk if there are any examples of this stuff YET on the SDK, but good luck!

Here you have BattleAxeVR's OpenXR SDK repo, that he is using for testing the new eye traking & body traking of the Quest Pro, so maybe there is somethig there that is interesting to you!
[https://github.com/BattleAxeVR/OpenXR-SDK-Source](https://github.com/BattleAxeVR/OpenXR-SDK-Source)

**Comment by SlimeVRX** [comment]
Hi, 

Thank you for your feedback! Thanks for your suggestion, I will follow BattleAxeVR
